name: Build and Upload Spring Boot BootJar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Make Gradle wrapper executable
      run: chmod +x gradlew

    - name: Build project
      run: ./gradlew clean build --stacktrace

    - name: Find Spring Boot executable JAR
      id: bootjar
      run: |
        BOOT_JAR=$(find build/libs -maxdepth 1 -type f -name "*.jar" ! -name "*plain*.jar")
        BOOT_JAR_NAME=$(basename "$BOOT_JAR")
        echo "BOOT_JAR=$BOOT_JAR_NAME" >> $GITHUB_ENV
        echo "artifact_name=${BOOT_JAR_NAME%.*}" >> $GITHUB_OUTPUT

    - name: Upload Spring Boot executable JAR
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.bootjar.outputs.artifact_name }}
        path: build/libs/${{ env.BOOT_JAR }}
