name: Build and Upload Spring Boot JAR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Build and test
      run: ./gradlew clean build --stacktrace

    - name: Get JAR filename
      id: get-jar
      run: |
        JAR_NAME=$(basename build/libs/*.jar)
        echo "JAR_NAME=$JAR_NAME" >> $GITHUB_ENV
        ARTIFACT_NAME="${JAR_NAME%.*}"
        echo "artifact_name=$ARTIFACT_NAME" >> "$GITHUB_OUTPUT"

    - name: Upload JAR with dynamic artifact name
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.get-jar.outputs.artifact_name }}
        path: build/libs/${{ env.JAR_NAME }}
